# Train and evaluate models

Single end-to-end pipeline. Each section runs in order and produces
results saved into `results/predictions.pkl` for notebook 04 to consume ;p yum

**Flow**
1. Setup + data
2. Logistic regression baseline
3. XGBoost: strongest tabular baseline (DLs greatest op)
4. MLP initial training
5. Supervised autoencoder (SAE) initial training
6. Hyperparameter sweep (MLP + SAE) selects the best config
7. Retrain MLP and SAE at the sweep-winning configs
8. Further SAE experiments (none of these improved model oops)
9. Final comparison table + save predictions and checkpoints

In [1]:
# colab setup
import sys, os, subprocess

IN_COLAB = 'google.colab' in sys.modules
PROJECT_DIR_DRIVE = '/content/drive/MyDrive/final_project'

if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=False)
    PROJECT_DIR = PROJECT_DIR_DRIVE
    subprocess.run(['pip', 'install', '-q', 'scanpy', 'umap-learn', 'xgboost'], check=True)
else:
    PROJECT_DIR = os.path.abspath(os.path.join(os.getcwd(), '..'))

os.chdir(PROJECT_DIR)
if PROJECT_DIR not in sys.path:
    sys.path.insert(0, PROJECT_DIR)

DATA_DIR = os.path.join(PROJECT_DIR, 'data')
RESULTS_DIR = os.path.join(PROJECT_DIR, 'results')
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(os.path.join(RESULTS_DIR, 'figures'), exist_ok=True)
os.makedirs(os.path.join(RESULTS_DIR, 'models'), exist_ok=True)
print('PROJECT_DIR =', PROJECT_DIR)

Mounted at /content/drive
PROJECT_DIR = /content/drive/MyDrive/final_project

### Step 1. Imports and data

In [2]:
import importlib
import pickle
from pathlib import Path

import anndata as ad
import numpy as np
import pandas as pd
import torch
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score, average_precision_score

from src import data as D
from src import train as T
from src import evaluate as E

T.set_seed(0)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('device:', device)
## RUN IN T4 HIGH RAM ELSE TAKES FIVEVER!!
adata = ad.read_h5ad(Path(DATA_DIR) / 'processed.h5ad')
print(adata)

device: cuda
AnnData object with n_obs × n_vars = 95790 × 2000
    obs: 'sample', 'UMAP_1', 'UMAP_2', 'ident', 'patient', 'source', 'clonotype', 'clone_size', 'expanded', 'n_genes_by_counts', 'total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'pct_counts_mt', 'n_genes', 'split'
    var: 'gene_id', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'hvg', 'log1p'
    layers: 'counts'

In [3]:
def split_arrays(adata, split):
    sub = adata[adata.obs['split'] == split]
    return D.to_matrix(sub), sub.obs['expanded'].values.astype(np.float32)

X_train, y_train = split_arrays(adata, 'train')
X_val,   y_val   = split_arrays(adata, 'val')
X_test,  y_test  = split_arrays(adata, 'test')
gene_names = list(adata.var_names)

print('train:', X_train.shape, 'pos frac', y_train.mean())
print('val:  ', X_val.shape,   'pos frac', y_val.mean())
print('test: ', X_test.shape,  'pos frac', y_test.mean())

train: (65435, 2000) pos frac 0.4967372
val:   (14224, 2000) pos frac 0.5857002
test:  (16131, 2000) pos frac 0.49060816

## Step 2: logistic regression baseline
L2-regularized logistic regression with `class_weight='balanced'`.  Reference point for how much non-linearity buys.

In [4]:
logreg = LogisticRegression(max_iter=1000, n_jobs=-1, class_weight='balanced', C=1.0)
logreg.fit(X_train, y_train)
p_logreg_val  = logreg.predict_proba(X_val)[:, 1]
p_logreg_test = logreg.predict_proba(X_test)[:, 1]
print('val :', E.classification_metrics(y_val,  p_logreg_val))
print('test:', E.classification_metrics(y_test, p_logreg_test))

val : {'auroc': 0.8002726084871725, 'auprc': 0.8148083829040322, 'f1': 0.7749662203660483, 'positive_rate': 0.5857002139091492, 'threshold': 0.5}
test: {'auroc': 0.7881968904558124, 'auprc': 0.7510177433180918, 'f1': 0.7252283034105734, 'positive_rate': 0.4906081557273865, 'threshold': 0.5}

## Step 3. XGBoost (strongest tabular baseline)

Gradient-boosted trees, no preprocessing changes... Often the best  model for moderate-size tabular biology data.

In [5]:
xgb = XGBClassifier(
    n_estimators=500, max_depth=6, learning_rate=0.05,
    n_jobs=-1, eval_metric='auc', tree_method='hist',
    device='cuda' if torch.cuda.is_available() else 'cpu',
)
xgb.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=False)
p_xgb_val  = xgb.predict_proba(X_val)[:, 1]
p_xgb_test = xgb.predict_proba(X_test)[:, 1]
print('val :', E.classification_metrics(y_val,  p_xgb_val))
print('test:', E.classification_metrics(y_test, p_xgb_test))

top_xgb = (pd.Series(xgb.feature_importances_, index=gene_names)
             .sort_values(ascending=False).head(30))
top_xgb

/usr/local/lib/python3.12/dist-packages/xgboost/core.py:751: UserWarning: [20:32:47] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

val : {'auroc': 0.8311931583164685, 'auprc': 0.8601306089152051, 'f1': 0.8020914718432598, 'positive_rate': 0.5857002139091492, 'threshold': 0.5}
test: {'auroc': 0.8108133285933189, 'auprc': 0.7658293111905711, 'f1': 0.7499844556363863, 'positive_rate': 0.4906081557273865, 'threshold': 0.5}

NKG7            0.089185
EEF1A1          0.017778
GZMH            0.017651
CCL4            0.011454
SELL            0.011081
CCR7            0.008637
XCL1            0.008249
CXCR6           0.007850
PASK            0.006506
HOPX            0.006465
GZMB            0.006325
ZNF683          0.005692
CD8A            0.005296
DUSP4           0.005239
CST7            0.004174
XCL2            0.004015
RGS1            0.003871
KLF2            0.003836
ANKRD28         0.003713
RTKN2           0.003544
FOXP3           0.003532
PTMS            0.003468
TNFRSF4         0.003436
IFNG            0.003269
CXCL13          0.003256
LOC101928152    0.003196
CH25H           0.003114
HLA-DRB5        0.003061
LOC101929531    0.003038
GZMK            0.003008
dtype: float32

## Step 4. MLP initial training

Default config (lr=1e-3, hidden=(512,128), dropout=0.3). Sweep in step 5 will tune this; the result here is the untuned baseline

In [6]:
cfg = T.TrainConfig(epochs=20, batch_size=512, lr=1e-3)
mlp_init, mlp_init_hist = T.train_mlp(
    X_train, y_train, X_val, y_val,
    in_features=X_train.shape[1], cfg=cfg,
)
p_mlp_init_val  = T.predict_proba(mlp_init, X_val)
p_mlp_init_test = T.predict_proba(mlp_init, X_test)
print('val :', E.classification_metrics(y_val,  p_mlp_init_val))
print('test:', E.classification_metrics(y_test, p_mlp_init_test))

epoch   1/20  train=0.4911  val=0.5141
epoch   2/20  train=0.4477  val=0.5031
epoch   3/20  train=0.4268  val=0.5077
epoch   4/20  train=0.4000  val=0.5383
epoch   5/20  train=0.3693  val=0.5511
epoch   6/20  train=0.3367  val=0.6012
epoch   7/20  train=0.2955  val=0.5914
epoch   8/20  train=0.2590  val=0.6818
epoch   9/20  train=0.2278  val=0.7343
epoch  10/20  train=0.1992  val=0.7053
epoch  11/20  train=0.1740  val=0.8403
epoch  12/20  train=0.1512  val=0.8683
epoch  13/20  train=0.1343  val=0.8924
epoch  14/20  train=0.1212  val=0.9480
epoch  15/20  train=0.1083  val=0.9593
epoch  16/20  train=0.0988  val=0.9842
epoch  17/20  train=0.0916  val=1.0998
epoch  18/20  train=0.0806  val=1.1304
epoch  19/20  train=0.0767  val=1.1477
epoch  20/20  train=0.0734  val=1.1652
val : {'auroc': 0.7811345805707323, 'auprc': 0.8006281162518601, 'f1': 0.7507034327518289, 'positive_rate': 0.5857002139091492, 'threshold': 0.5}
test: {'auroc': 0.7708652746857119, 'auprc': 0.7377973267917484, 'f1': 0.7069373520986424, 'positive_rate': 0.4906081557273865, 'threshold': 0.5}

## Step 5. Supervised autoencoder initial training

Joint loss = `recon_weight · MSE(decoder(z), x) + clf_weight · BCE(logit, y)`. Starting point: equal-ish weights, latent_dim=32.

In [7]:
cfg = T.TrainConfig(epochs=30, batch_size=512, lr=1e-3,
                    recon_weight=1.0, clf_weight=2.0)
sae_init, sae_init_hist = T.train_sae(
    X_train, y_train, X_val, y_val,
    in_features=X_train.shape[1], cfg=cfg,
    hidden_dims=(512, 128), latent_dim=32, dropout=0.2,
)
p_sae_init_val  = T.predict_proba(sae_init, X_val)
p_sae_init_test = T.predict_proba(sae_init, X_test)
print('val :', E.classification_metrics(y_val,  p_sae_init_val))
print('test:', E.classification_metrics(y_test, p_sae_init_test))

epoch   1/30  train: loss=1.1076 recon=0.1088 clf=0.4994  val: loss=1.1394 recon=0.1011 clf=0.5192
epoch   2/30  train: loss=0.9970 recon=0.0900 clf=0.4535  val: loss=1.1424 recon=0.0961 clf=0.5232
epoch   3/30  train: loss=0.9489 recon=0.0861 clf=0.4314  val: loss=1.1103 recon=0.0940 clf=0.5081
epoch   4/30  train: loss=0.8950 recon=0.0843 clf=0.4054  val: loss=1.1473 recon=0.0928 clf=0.5272
epoch   5/30  train: loss=0.8289 recon=0.0831 clf=0.3729  val: loss=1.1695 recon=0.0917 clf=0.5389
epoch   6/30  train: loss=0.7470 recon=0.0824 clf=0.3323  val: loss=1.2443 recon=0.0919 clf=0.5762
epoch   7/30  train: loss=0.6658 recon=0.0821 clf=0.2919  val: loss=1.3664 recon=0.0912 clf=0.6376
epoch   8/30  train: loss=0.5836 recon=0.0820 clf=0.2508  val: loss=1.6660 recon=0.0913 clf=0.7873
epoch   9/30  train: loss=0.5154 recon=0.0822 clf=0.2166  val: loss=1.6657 recon=0.0920 clf=0.7868
epoch  10/30  train: loss=0.4590 recon=0.0822 clf=0.1884  val: loss=1.9861 recon=0.0913 clf=0.9474
epoch  11/30  train: loss=0.4043 recon=0.0822 clf=0.1610  val: loss=2.0794 recon=0.0921 clf=0.9936
epoch  12/30  train: loss=0.3656 recon=0.0819 clf=0.1418  val: loss=2.1287 recon=0.0919 clf=1.0184
epoch  13/30  train: loss=0.3201 recon=0.0818 clf=0.1192  val: loss=2.3734 recon=0.0919 clf=1.1408
epoch  14/30  train: loss=0.3006 recon=0.0817 clf=0.1094  val: loss=2.3309 recon=0.0920 clf=1.1194
epoch  15/30  train: loss=0.2691 recon=0.0817 clf=0.0937  val: loss=2.3964 recon=0.0922 clf=1.1521
epoch  16/30  train: loss=0.2522 recon=0.0817 clf=0.0853  val: loss=2.4284 recon=0.0923 clf=1.1681
epoch  17/30  train: loss=0.2303 recon=0.0815 clf=0.0744  val: loss=2.7440 recon=0.0916 clf=1.3262
epoch  18/30  train: loss=0.2164 recon=0.0814 clf=0.0675  val: loss=2.6522 recon=0.0926 clf=1.2798
epoch  19/30  train: loss=0.2073 recon=0.0812 clf=0.0630  val: loss=2.7078 recon=0.0915 clf=1.3082
epoch  20/30  train: loss=0.1980 recon=0.0811 clf=0.0584  val: loss=2.8197 recon=0.0924 clf=1.3636
epoch  21/30  train: loss=0.1850 recon=0.0812 clf=0.0519  val: loss=2.9342 recon=0.0916 clf=1.4213
epoch  22/30  train: loss=0.1779 recon=0.0811 clf=0.0484  val: loss=3.0320 recon=0.0916 clf=1.4702
epoch  23/30  train: loss=0.1800 recon=0.0810 clf=0.0495  val: loss=2.9991 recon=0.0918 clf=1.4537
epoch  24/30  train: loss=0.1690 recon=0.0808 clf=0.0441  val: loss=3.1487 recon=0.0914 clf=1.5287
epoch  25/30  train: loss=0.1617 recon=0.0807 clf=0.0405  val: loss=3.1910 recon=0.0911 clf=1.5500
epoch  26/30  train: loss=0.1585 recon=0.0807 clf=0.0389  val: loss=3.1671 recon=0.0909 clf=1.5381
epoch  27/30  train: loss=0.1613 recon=0.0806 clf=0.0403  val: loss=3.2707 recon=0.0915 clf=1.5896
epoch  28/30  train: loss=0.1610 recon=0.0805 clf=0.0402  val: loss=3.0830 recon=0.0910 clf=1.4960
epoch  29/30  train: loss=0.1541 recon=0.0805 clf=0.0368  val: loss=3.2837 recon=0.0908 clf=1.5965
epoch  30/30  train: loss=0.1485 recon=0.0804 clf=0.0341  val: loss=3.2891 recon=0.0911 clf=1.5990
val : {'auroc': 0.7881201170402038, 'auprc': 0.8132424917644909, 'f1': 0.7397645854657113, 'positive_rate': 0.5857002139091492, 'threshold': 0.5}
test: {'auroc': 0.7670816439804446, 'auprc': 0.7297929478205358, 'f1': 0.6947274008584791, 'positive_rate': 0.4906081557273865, 'threshold': 0.5}

## STEP 6. Hyperparameter sweep

Small grid/model. Best config is selected on **val AUROC**  only, test predictions in step 6 use the winning config retrained from scratch

In [8]:
records = []

# MLP grid
mlp_grid = [
    dict(lr=1e-3, hidden_dims=(512, 128), dropout=0.3),   # og
    dict(lr=3e-4, hidden_dims=(512, 128), dropout=0.3),
    dict(lr=3e-4, hidden_dims=(256,),     dropout=0.1),
    dict(lr=1e-4, hidden_dims=(256, 64),  dropout=0.1),
]
for i, hp in enumerate(mlp_grid):
    cfg = T.TrainConfig(epochs=25, batch_size=512, lr=hp['lr'], weight_decay=1e-4)
    print(f'\nMLP run {i+1}/{len(mlp_grid)}: {hp}')
    m, _ = T.train_mlp(X_train, y_train, X_val, y_val,
                       in_features=X_train.shape[1], cfg=cfg,
                       hidden_dims=hp['hidden_dims'], dropout=hp['dropout'])
    p_val = T.predict_proba(m, X_val)
    records.append({'model': 'mlp', **hp,
                    'val_auroc': roc_auc_score(y_val, p_val),
                    'val_auprc': average_precision_score(y_val, p_val)})

# SAE grid
sae_grid = [
    dict(lr=1e-3, recon_w=1.0, clf_w=2.0,  latent=32, hidden=(512,128), dropout=0.2),
    dict(lr=3e-4, recon_w=0.1, clf_w=10.0, latent=32, hidden=(512,128), dropout=0.2),
    dict(lr=3e-4, recon_w=0.5, clf_w=5.0,  latent=16, hidden=(256, 64), dropout=0.1),
    dict(lr=3e-4, recon_w=1.0, clf_w=1.0,  latent=64, hidden=(512,128), dropout=0.2),
]
for i, hp in enumerate(sae_grid):
    cfg = T.TrainConfig(epochs=30, batch_size=512, lr=hp['lr'], weight_decay=1e-4,
                        recon_weight=hp['recon_w'], clf_weight=hp['clf_w'])
    print(f'\nSAE run {i+1}/{len(sae_grid)}: {hp}')
    m, _ = T.train_sae(X_train, y_train, X_val, y_val,
                       in_features=X_train.shape[1], cfg=cfg,
                       hidden_dims=hp['hidden'], latent_dim=hp['latent'],
                       dropout=hp['dropout'])
    p_val = T.predict_proba(m, X_val)
    records.append({'model': 'sae', **hp,
                    'val_auroc': roc_auc_score(y_val, p_val),
                    'val_auprc': average_precision_score(y_val, p_val)})

sweep_df = (pd.DataFrame(records)
              .sort_values(['model', 'val_auroc'], ascending=[True, False])
              .reset_index(drop=True))
sweep_df.to_csv(Path(RESULTS_DIR) / 'hp_sweep.csv', index=False)
sweep_df

MLP run 1/4: {'lr': 0.001, 'hidden_dims': (512, 128), 'dropout': 0.3}
epoch   1/25  train=0.4913  val=0.5141
epoch   2/25  train=0.4493  val=0.5072
epoch   3/25  train=0.4312  val=0.5186
epoch   4/25  train=0.4101  val=0.5228
epoch   5/25  train=0.3869  val=0.5212
epoch   6/25  train=0.3624  val=0.5564
epoch   7/25  train=0.3324  val=0.5577
epoch   8/25  train=0.3007  val=0.6138
epoch   9/25  train=0.2732  val=0.6454
epoch  10/25  train=0.2504  val=0.6426
epoch  11/25  train=0.2225  val=0.7056
epoch  12/25  train=0.1991  val=0.7649
epoch  13/25  train=0.1826  val=0.7587
epoch  14/25  train=0.1686  val=0.7913
epoch  15/25  train=0.1546  val=0.8280
epoch  16/25  train=0.1402  val=0.9658
epoch  17/25  train=0.1333  val=0.9624
epoch  18/25  train=0.1239  val=0.9571
epoch  19/25  train=0.1149  val=0.9651
epoch  20/25  train=0.1083  val=0.9996
epoch  21/25  train=0.1013  val=0.9871
epoch  22/25  train=0.0968  val=1.0157
epoch  23/25  train=0.0977  val=1.0754
epoch  24/25  train=0.0908  val=1.0504
epoch  25/25  train=0.0906  val=1.0173

MLP run 2/4: {'lr': 0.0003, 'hidden_dims': (512, 128), 'dropout': 0.3}
epoch   1/25  train=0.5151  val=0.5172
epoch   2/25  train=0.4614  val=0.5160
epoch   3/25  train=0.4443  val=0.5132
epoch   4/25  train=0.4264  val=0.5266
epoch   5/25  train=0.4076  val=0.5481
epoch   6/25  train=0.3834  val=0.5259
epoch   7/25  train=0.3561  val=0.5346
epoch   8/25  train=0.3227  val=0.5613
epoch   9/25  train=0.2889  val=0.5859
epoch  10/25  train=0.2549  val=0.5916
epoch  11/25  train=0.2229  val=0.6377
epoch  12/25  train=0.1897  val=0.6805
epoch  13/25  train=0.1658  val=0.7366
epoch  14/25  train=0.1418  val=0.7808
epoch  15/25  train=0.1260  val=0.8365
epoch  16/25  train=0.1076  val=0.8498
epoch  17/25  train=0.0973  val=0.9073
epoch  18/25  train=0.0838  val=0.9334
epoch  19/25  train=0.0775  val=0.9444
epoch  20/25  train=0.0716  val=1.0048
epoch  21/25  train=0.0666  val=1.0027
epoch  22/25  train=0.0605  val=1.0430
epoch  23/25  train=0.0577  val=1.0675
epoch  24/25  train=0.0546  val=1.0824
epoch  25/25  train=0.0517  val=1.0780

MLP run 3/4: {'lr': 0.0003, 'hidden_dims': (256,), 'dropout': 0.1}
epoch   1/25  train=0.5182  val=0.5301
epoch   2/25  train=0.4729  val=0.5165
epoch   3/25  train=0.4591  val=0.5208
epoch   4/25  train=0.4486  val=0.5076
epoch   5/25  train=0.4380  val=0.5041
epoch   6/25  train=0.4285  val=0.5039
epoch   7/25  train=0.4189  val=0.5094
epoch   8/25  train=0.4105  val=0.5019
epoch   9/25  train=0.4010  val=0.4979
epoch  10/25  train=0.3927  val=0.4998
epoch  11/25  train=0.3829  val=0.5151
epoch  12/25  train=0.3732  val=0.5154
epoch  13/25  train=0.3623  val=0.5150
epoch  14/25  train=0.3530  val=0.5300
epoch  15/25  train=0.3421  val=0.5196
epoch  16/25  train=0.3315  val=0.5177
epoch  17/25  train=0.3196  val=0.5237
epoch  18/25  train=0.3085  val=0.5356
epoch  19/25  train=0.2979  val=0.5434
epoch  20/25  train=0.2855  val=0.5454
epoch  21/25  train=0.2746  val=0.5366
epoch  22/25  train=0.2647  val=0.5421
epoch  23/25  train=0.2525  val=0.5622
epoch  24/25  train=0.2425  val=0.5581
epoch  25/25  train=0.2330  val=0.5961

MLP run 4/4: {'lr': 0.0001, 'hidden_dims': (256, 64), 'dropout': 0.1}
epoch   1/25  train=0.5781  val=0.5489
epoch   2/25  train=0.4907  val=0.5264
epoch   3/25  train=0.4762  val=0.5236
epoch   4/25  train=0.4670  val=0.5201
epoch   5/25  train=0.4594  val=0.5255
epoch   6/25  train=0.4516  val=0.5154
epoch   7/25  train=0.4437  val=0.5136
epoch   8/25  train=0.4356  val=0.5048
epoch   9/25  train=0.4272  val=0.5049
epoch  10/25  train=0.4193  val=0.5003
epoch  11/25  train=0.4101  val=0.5143
epoch  12/25  train=0.4015  val=0.5136
epoch  13/25  train=0.3912  val=0.5148
epoch  14/25  train=0.3828  val=0.5269
epoch  15/25  train=0.3726  val=0.5389
epoch  16/25  train=0.3634  val=0.5130
epoch  17/25  train=0.3531  val=0.5249
epoch  18/25  train=0.3414  val=0.5394
epoch  19/25  train=0.3297  val=0.5337
epoch  20/25  train=0.3196  val=0.5500
epoch  21/25  train=0.3086  val=0.5594
epoch  22/25  train=0.2957  val=0.5795
epoch  23/25  train=0.2838  val=0.5867
epoch  24/25  train=0.2723  val=0.5746
epoch  25/25  train=0.2584  val=0.5960

SAE run 1/4: {'lr': 0.001, 'recon_w': 1.0, 'clf_w': 2.0, 'latent': 32, 'hidden': (512, 128), 'dropout': 0.2}
epoch   1/30  train: loss=1.1067 recon=0.1072 clf=0.4998  val: loss=1.1429 recon=0.1004 clf=0.5213
epoch   2/30  train: loss=1.0013 recon=0.0907 clf=0.4553  val: loss=1.1615 recon=0.0987 clf=0.5314
epoch   3/30  train: loss=0.9597 recon=0.0882 clf=0.4358  val: loss=1.1245 recon=0.0980 clf=0.5133
epoch   4/30  train: loss=0.9139 recon=0.0870 clf=0.4134  val: loss=1.1408 recon=0.0961 clf=0.5223
epoch   5/30  train: loss=0.8583 recon=0.0863 clf=0.3860  val: loss=1.1596 recon=0.0959 clf=0.5318
epoch   6/30  train: loss=0.7969 recon=0.0862 clf=0.3553  val: loss=1.1855 recon=0.0951 clf=0.5452
epoch   7/30  train: loss=0.7260 recon=0.0861 clf=0.3200  val: loss=1.4032 recon=0.0946 clf=0.6543
epoch   8/30  train: loss=0.6585 recon=0.0863 clf=0.2861  val: loss=1.5035 recon=0.0961 clf=0.7037
epoch   9/30  train: loss=0.5889 recon=0.0861 clf=0.2514  val: loss=1.4903 recon=0.0949 clf=0.6977
epoch  10/30  train: loss=0.5270 recon=0.0860 clf=0.2205  val: loss=1.8961 recon=0.0948 clf=0.9006
epoch  11/30  train: loss=0.4783 recon=0.0860 clf=0.1961  val: loss=1.8463 recon=0.0960 clf=0.8752
epoch  12/30  train: loss=0.4368 recon=0.0862 clf=0.1753  val: loss=2.0482 recon=0.0957 clf=0.9763
epoch  13/30  train: loss=0.3915 recon=0.0861 clf=0.1527  val: loss=1.9435 recon=0.0965 clf=0.9235
epoch  14/30  train: loss=0.3517 recon=0.0859 clf=0.1329  val: loss=2.0146 recon=0.0965 clf=0.9591
epoch  15/30  train: loss=0.3259 recon=0.0861 clf=0.1199  val: loss=2.1732 recon=0.0963 clf=1.0384
epoch  16/30  train: loss=0.3025 recon=0.0858 clf=0.1083  val: loss=2.2538 recon=0.0964 clf=1.0787
epoch  17/30  train: loss=0.2803 recon=0.0858 clf=0.0973  val: loss=2.3321 recon=0.0954 clf=1.1184
epoch  18/30  train: loss=0.2667 recon=0.0856 clf=0.0906  val: loss=2.4484 recon=0.0968 clf=1.1758
epoch  19/30  train: loss=0.2531 recon=0.0856 clf=0.0837  val: loss=2.5260 recon=0.0960 clf=1.2150
epoch  20/30  train: loss=0.2432 recon=0.0854 clf=0.0789  val: loss=2.4550 recon=0.0974 clf=1.1788
epoch  21/30  train: loss=0.2283 recon=0.0854 clf=0.0714  val: loss=2.5893 recon=0.0958 clf=1.2467
epoch  22/30  train: loss=0.2219 recon=0.0853 clf=0.0683  val: loss=2.6039 recon=0.0953 clf=1.2543
epoch  23/30  train: loss=0.2185 recon=0.0851 clf=0.0667  val: loss=2.4634 recon=0.0953 clf=1.1841
epoch  24/30  train: loss=0.2124 recon=0.0852 clf=0.0636  val: loss=2.6534 recon=0.0956 clf=1.2789
epoch  25/30  train: loss=0.2040 recon=0.0851 clf=0.0595  val: loss=2.6720 recon=0.0945 clf=1.2888
epoch  26/30  train: loss=0.1947 recon=0.0848 clf=0.0550  val: loss=2.6775 recon=0.0947 clf=1.2914
epoch  27/30  train: loss=0.2000 recon=0.0849 clf=0.0575  val: loss=2.5578 recon=0.0953 clf=1.2313
epoch  28/30  train: loss=0.1938 recon=0.0849 clf=0.0545  val: loss=2.7573 recon=0.0951 clf=1.3311
epoch  29/30  train: loss=0.1925 recon=0.0846 clf=0.0540  val: loss=2.6774 recon=0.0946 clf=1.2914
epoch  30/30  train: loss=0.1895 recon=0.0846 clf=0.0524  val: loss=2.7569 recon=0.0943 clf=1.3313

SAE run 2/4: {'lr': 0.0003, 'recon_w': 0.1, 'clf_w': 10.0, 'latent': 32, 'hidden': (512, 128), 'dropout': 0.2}
epoch   1/30  train: loss=5.2973 recon=0.1264 clf=0.5285  val: loss=5.3472 recon=0.1039 clf=0.5337
epoch   2/30  train: loss=4.7075 recon=0.0960 clf=0.4698  val: loss=5.4265 recon=0.1059 clf=0.5416
epoch   3/30  train: loss=4.5399 recon=0.0959 clf=0.4530  val: loss=5.0575 recon=0.1081 clf=0.5047
epoch   4/30  train: loss=4.3485 recon=0.0966 clf=0.4339  val: loss=5.1284 recon=0.1106 clf=0.5117
epoch   5/30  train: loss=4.1212 recon=0.0972 clf=0.4111  val: loss=5.0419 recon=0.1098 clf=0.5031
epoch   6/30  train: loss=3.8261 recon=0.0972 clf=0.3816  val: loss=5.1576 recon=0.1102 clf=0.5147
epoch   7/30  train: loss=3.4560 recon=0.0977 clf=0.3446  val: loss=5.6251 recon=0.1097 clf=0.5614
epoch   8/30  train: loss=3.0368 recon=0.0983 clf=0.3027  val: loss=6.5647 recon=0.1109 clf=0.6554
epoch   9/30  train: loss=2.5462 recon=0.0984 clf=0.2536  val: loss=6.7358 recon=0.1108 clf=0.6725
epoch  10/30  train: loss=2.1381 recon=0.0985 clf=0.2128  val: loss=7.7497 recon=0.1110 clf=0.7739
epoch  11/30  train: loss=1.8097 recon=0.0984 clf=0.1800  val: loss=9.0246 recon=0.1110 clf=0.9013
epoch  12/30  train: loss=1.4790 recon=0.0984 clf=0.1469  val: loss=9.7501 recon=0.1108 clf=0.9739
epoch  13/30  train: loss=1.2138 recon=0.0984 clf=0.1204  val: loss=9.8265 recon=0.1116 clf=0.9815
epoch  14/30  train: loss=1.0026 recon=0.0985 clf=0.0993  val: loss=10.6733 recon=0.1117 clf=1.0662
epoch  15/30  train: loss=0.9050 recon=0.0985 clf=0.0895  val: loss=11.6569 recon=0.1118 clf=1.1646
epoch  16/30  train: loss=0.8006 recon=0.0986 clf=0.0791  val: loss=12.2428 recon=0.1119 clf=1.2232
epoch  17/30  train: loss=0.6926 recon=0.0987 clf=0.0683  val: loss=12.6091 recon=0.1118 clf=1.2598
epoch  18/30  train: loss=0.5785 recon=0.0987 clf=0.0569  val: loss=12.5581 recon=0.1147 clf=1.2547
epoch  19/30  train: loss=0.5038 recon=0.0989 clf=0.0494  val: loss=14.2710 recon=0.1118 clf=1.4260
epoch  20/30  train: loss=0.4739 recon=0.0988 clf=0.0464  val: loss=13.9299 recon=0.1131 clf=1.3919
epoch  21/30  train: loss=0.4389 recon=0.0988 clf=0.0429  val: loss=14.3090 recon=0.1133 clf=1.4298
epoch  22/30  train: loss=0.3957 recon=0.0989 clf=0.0386  val: loss=14.5713 recon=0.1129 clf=1.4560
epoch  23/30  train: loss=0.4260 recon=0.0988 clf=0.0416  val: loss=14.2323 recon=0.1135 clf=1.4221
epoch  24/30  train: loss=0.3748 recon=0.0988 clf=0.0365  val: loss=15.1872 recon=0.1133 clf=1.5176
epoch  25/30  train: loss=0.3282 recon=0.0988 clf=0.0318  val: loss=15.7567 recon=0.1121 clf=1.5745
epoch  26/30  train: loss=0.3303 recon=0.0988 clf=0.0320  val: loss=15.0397 recon=0.1134 clf=1.5028
epoch  27/30  train: loss=0.3023 recon=0.0988 clf=0.0292  val: loss=16.2480 recon=0.1136 clf=1.6237
epoch  28/30  train: loss=0.3116 recon=0.0988 clf=0.0302  val: loss=15.0675 recon=0.1125 clf=1.5056
epoch  29/30  train: loss=0.2996 recon=0.0988 clf=0.0290  val: loss=15.3080 recon=0.1130 clf=1.5297
epoch  30/30  train: loss=0.2862 recon=0.0988 clf=0.0276  val: loss=15.7754 recon=0.1137 clf=1.5764

SAE run 3/4: {'lr': 0.0003, 'recon_w': 0.5, 'clf_w': 5.0, 'latent': 16, 'hidden': (256, 64), 'dropout': 0.1}
epoch   1/30  train: loss=2.8276 recon=0.1372 clf=0.5518  val: loss=2.7165 recon=0.1034 clf=0.5330
epoch   2/30  train: loss=2.4437 recon=0.0953 clf=0.4792  val: loss=2.7038 recon=0.1020 clf=0.5306
epoch   3/30  train: loss=2.3755 recon=0.0935 clf=0.4657  val: loss=2.6355 recon=0.1026 clf=0.5168
epoch   4/30  train: loss=2.3016 recon=0.0930 clf=0.4510  val: loss=2.5740 recon=0.1030 clf=0.5045
epoch   5/30  train: loss=2.2304 recon=0.0929 clf=0.4368  val: loss=2.5893 recon=0.1035 clf=0.5075
epoch   6/30  train: loss=2.1590 recon=0.0930 clf=0.4225  val: loss=2.7235 recon=0.1036 clf=0.5343
epoch   7/30  train: loss=2.0722 recon=0.0931 clf=0.4051  val: loss=2.6247 recon=0.1040 clf=0.5145
epoch   8/30  train: loss=1.9741 recon=0.0930 clf=0.3855  val: loss=2.7618 recon=0.1035 clf=0.5420
epoch   9/30  train: loss=1.8683 recon=0.0932 clf=0.3643  val: loss=2.7183 recon=0.1039 clf=0.5333
epoch  10/30  train: loss=1.7375 recon=0.0935 clf=0.3382  val: loss=2.8364 recon=0.1039 clf=0.5569
epoch  11/30  train: loss=1.5975 recon=0.0936 clf=0.3101  val: loss=3.0093 recon=0.1036 clf=0.5915
epoch  12/30  train: loss=1.4553 recon=0.0937 clf=0.2817  val: loss=3.6006 recon=0.1029 clf=0.7098
epoch  13/30  train: loss=1.3043 recon=0.0933 clf=0.2515  val: loss=3.4178 recon=0.1029 clf=0.6733
epoch  14/30  train: loss=1.1773 recon=0.0926 clf=0.2262  val: loss=3.9409 recon=0.1020 clf=0.7780
epoch  15/30  train: loss=1.0376 recon=0.0919 clf=0.1983  val: loss=4.0668 recon=0.1021 clf=0.8032
epoch  16/30  train: loss=0.9417 recon=0.0916 clf=0.1792  val: loss=4.3071 recon=0.1023 clf=0.8512
epoch  17/30  train: loss=0.8428 recon=0.0916 clf=0.1594  val: loss=4.7931 recon=0.1022 clf=0.9484
epoch  18/30  train: loss=0.7346 recon=0.0914 clf=0.1378  val: loss=5.3983 recon=0.1017 clf=1.0695
epoch  19/30  train: loss=0.6596 recon=0.0913 clf=0.1228  val: loss=5.6605 recon=0.1021 clf=1.1219
epoch  20/30  train: loss=0.6116 recon=0.0913 clf=0.1132  val: loss=5.6209 recon=0.1021 clf=1.1140
epoch  21/30  train: loss=0.5376 recon=0.0912 clf=0.0984  val: loss=6.2785 recon=0.1022 clf=1.2455
epoch  22/30  train: loss=0.5043 recon=0.0914 clf=0.0917  val: loss=6.4695 recon=0.1021 clf=1.2837
epoch  23/30  train: loss=0.4802 recon=0.0915 clf=0.0869  val: loss=6.9885 recon=0.1023 clf=1.3875
epoch  24/30  train: loss=0.4380 recon=0.0915 clf=0.0784  val: loss=7.3800 recon=0.1024 clf=1.4658
epoch  25/30  train: loss=0.3975 recon=0.0915 clf=0.0704  val: loss=6.8868 recon=0.1022 clf=1.3671
epoch  26/30  train: loss=0.3584 recon=0.0916 clf=0.0625  val: loss=7.6023 recon=0.1022 clf=1.5102
epoch  27/30  train: loss=0.3543 recon=0.0916 clf=0.0617  val: loss=7.2833 recon=0.1022 clf=1.4464
epoch  28/30  train: loss=0.3421 recon=0.0915 clf=0.0593  val: loss=7.0564 recon=0.1022 clf=1.4011
epoch  29/30  train: loss=0.3006 recon=0.0916 clf=0.0510  val: loss=7.8792 recon=0.1028 clf=1.5656
epoch  30/30  train: loss=0.2740 recon=0.0915 clf=0.0457  val: loss=8.2954 recon=0.1024 clf=1.6488

SAE run 4/4: {'lr': 0.0003, 'recon_w': 1.0, 'clf_w': 1.0, 'latent': 64, 'hidden': (512, 128), 'dropout': 0.2}
epoch   1/30  train: loss=0.6466 recon=0.1242 clf=0.5224  val: loss=0.6216 recon=0.1027 clf=0.5189
epoch   2/30  train: loss=0.5577 recon=0.0929 clf=0.4648  val: loss=0.6187 recon=0.1003 clf=0.5184
epoch   3/30  train: loss=0.5351 recon=0.0909 clf=0.4443  val: loss=0.6102 recon=0.0993 clf=0.5109
epoch   4/30  train: loss=0.5114 recon=0.0884 clf=0.4230  val: loss=0.6042 recon=0.0981 clf=0.5062
epoch   5/30  train: loss=0.4861 recon=0.0872 clf=0.3989  val: loss=0.6185 recon=0.0977 clf=0.5208
epoch   6/30  train: loss=0.4562 recon=0.0870 clf=0.3693  val: loss=0.6491 recon=0.0975 clf=0.5515
epoch   7/30  train: loss=0.4177 recon=0.0868 clf=0.3309  val: loss=0.6521 recon=0.0976 clf=0.5545
epoch   8/30  train: loss=0.3746 recon=0.0866 clf=0.2880  val: loss=0.7214 recon=0.0975 clf=0.6239
epoch   9/30  train: loss=0.3339 recon=0.0865 clf=0.2474  val: loss=0.7665 recon=0.0986 clf=0.6678
epoch  10/30  train: loss=0.2927 recon=0.0863 clf=0.2064  val: loss=0.8546 recon=0.0979 clf=0.7567
epoch  11/30  train: loss=0.2602 recon=0.0861 clf=0.1740  val: loss=0.9891 recon=0.0979 clf=0.8912
epoch  12/30  train: loss=0.2326 recon=0.0860 clf=0.1466  val: loss=1.0595 recon=0.0977 clf=0.9618
epoch  13/30  train: loss=0.2143 recon=0.0859 clf=0.1285  val: loss=1.0570 recon=0.0977 clf=0.9593
epoch  14/30  train: loss=0.1941 recon=0.0858 clf=0.1083  val: loss=1.1233 recon=0.0973 clf=1.0259
epoch  15/30  train: loss=0.1786 recon=0.0856 clf=0.0929  val: loss=1.2046 recon=0.0971 clf=1.1075
epoch  16/30  train: loss=0.1677 recon=0.0856 clf=0.0821  val: loss=1.2372 recon=0.0971 clf=1.1401
epoch  17/30  train: loss=0.1613 recon=0.0855 clf=0.0758  val: loss=1.2839 recon=0.0971 clf=1.1868
epoch  18/30  train: loss=0.1495 recon=0.0854 clf=0.0641  val: loss=1.3653 recon=0.0975 clf=1.2678
epoch  19/30  train: loss=0.1455 recon=0.0853 clf=0.0603  val: loss=1.4381 recon=0.0968 clf=1.3413
epoch  20/30  train: loss=0.1391 recon=0.0852 clf=0.0539  val: loss=1.4546 recon=0.0970 clf=1.3576
epoch  21/30  train: loss=0.1373 recon=0.0852 clf=0.0521  val: loss=1.4254 recon=0.0967 clf=1.3287
epoch  22/30  train: loss=0.1357 recon=0.0851 clf=0.0506  val: loss=1.4002 recon=0.0969 clf=1.3034
epoch  23/30  train: loss=0.1342 recon=0.0850 clf=0.0492  val: loss=1.3825 recon=0.0969 clf=1.2856
epoch  24/30  train: loss=0.1294 recon=0.0850 clf=0.0445  val: loss=1.4900 recon=0.0967 clf=1.3933
epoch  25/30  train: loss=0.1269 recon=0.0850 clf=0.0420  val: loss=1.5180 recon=0.0966 clf=1.4214
epoch  26/30  train: loss=0.1267 recon=0.0849 clf=0.0418  val: loss=1.5401 recon=0.0966 clf=1.4434
epoch  27/30  train: loss=0.1221 recon=0.0848 clf=0.0373  val: loss=1.5113 recon=0.0967 clf=1.4147
epoch  28/30  train: loss=0.1217 recon=0.0847 clf=0.0370  val: loss=1.4891 recon=0.0965 clf=1.3926
epoch  29/30  train: loss=0.1191 recon=0.0847 clf=0.0344  val: loss=1.5358 recon=0.0966 clf=1.4392
epoch  30/30  train: loss=0.1197 recon=0.0846 clf=0.0351  val: loss=1.5359 recon=0.0965 clf=1.4394

,model,lr,hidden_dims,dropout,val_auroc,val_auprc,recon_w,clf_w,latent,hidden
0,mlp,0.0003,"(256,)",0.1,0.817006,0.846849,NaN,NaN,NaN,NaN
1,mlp,0.0001,"(256, 64)",0.1,0.810398,0.840240,NaN,NaN,NaN,NaN
2,mlp,0.0003,"(512, 128)",0.3,0.791686,0.811650,NaN,NaN,NaN,NaN
3,mlp,0.0010,"(512, 128)",0.3,0.787243,0.805505,NaN,NaN,NaN,NaN
4,sae,0.0003,NaN,0.2,0.786774,0.803028,1.0,1.0,64.0,"(512, 128)"
5,sae,0.0003,NaN,0.2,0.783418,0.800203,0.1,10.0,32.0,"(512, 128)"
6,sae,0.0010,NaN,0.2,0.774356,0.795833,1.0,2.0,32.0,"(512, 128)"
7,sae,0.0003,NaN,0.1,0.755449,0.769520,0.5,5.0,16.0,"(256, 64)"

## Step 7. Retrain MLP and SAE at the sweep-winning configs

These models go into the final results BUNDLE! Test set is only touched here, never used to select configs!!!

In [9]:
best_mlp = sweep_df[sweep_df.model == 'mlp'].iloc[0]
best_sae = sweep_df[sweep_df.model == 'sae'].iloc[0]
print('best MLP:', dict(best_mlp))
print('best SAE:', dict(best_sae))

best MLP: {'model': 'mlp', 'lr': np.float64(0.0003), 'hidden_dims': (256,), 'dropout': np.float64(0.1), 'val_auroc': np.float64(0.817005533991398), 'val_auprc': np.float64(0.8468488002654398), 'recon_w': np.float64(nan), 'clf_w': np.float64(nan), 'latent': np.float64(nan), 'hidden': nan}
best SAE: {'model': 'sae', 'lr': np.float64(0.0003), 'hidden_dims': nan, 'dropout': np.float64(0.2), 'val_auroc': np.float64(0.7867739094555503), 'val_auprc': np.float64(0.8030278978920249), 'recon_w': np.float64(1.0), 'clf_w': np.float64(1.0), 'latent': np.float64(64.0), 'hidden': (512, 128)}

In [10]:
# BEST MLP
cfg = T.TrainConfig(epochs=25, batch_size=512, lr=best_mlp['lr'], weight_decay=1e-4)
mlp, mlp_hist = T.train_mlp(
    X_train, y_train, X_val, y_val,
    in_features=X_train.shape[1], cfg=cfg,
    hidden_dims=tuple(best_mlp['hidden_dims']),
    dropout=float(best_mlp['dropout']),
)
p_mlp_val  = T.predict_proba(mlp, X_val)
p_mlp_test = T.predict_proba(mlp, X_test)
print('val :', E.classification_metrics(y_val,  p_mlp_val))
print('test:', E.classification_metrics(y_test, p_mlp_test))

epoch   1/25  train=0.5182  val=0.5301
epoch   2/25  train=0.4729  val=0.5165
epoch   3/25  train=0.4591  val=0.5208
epoch   4/25  train=0.4486  val=0.5076
epoch   5/25  train=0.4380  val=0.5041
epoch   6/25  train=0.4285  val=0.5039
epoch   7/25  train=0.4189  val=0.5094
epoch   8/25  train=0.4105  val=0.5019
epoch   9/25  train=0.4010  val=0.4979
epoch  10/25  train=0.3927  val=0.4998
epoch  11/25  train=0.3829  val=0.5151
epoch  12/25  train=0.3732  val=0.5154
epoch  13/25  train=0.3623  val=0.5150
epoch  14/25  train=0.3530  val=0.5300
epoch  15/25  train=0.3421  val=0.5196
epoch  16/25  train=0.3315  val=0.5177
epoch  17/25  train=0.3196  val=0.5237
epoch  18/25  train=0.3085  val=0.5356
epoch  19/25  train=0.2979  val=0.5434
epoch  20/25  train=0.2855  val=0.5454
epoch  21/25  train=0.2746  val=0.5366
epoch  22/25  train=0.2647  val=0.5421
epoch  23/25  train=0.2525  val=0.5622
epoch  24/25  train=0.2425  val=0.5581
epoch  25/25  train=0.2330  val=0.5961
val : {'auroc': 0.817005533991398, 'auprc': 0.8468488002654398, 'f1': 0.7585274810142876, 'positive_rate': 0.5857002139091492, 'threshold': 0.5}
test: {'auroc': 0.775778726211237, 'auprc': 0.7382643164671079, 'f1': 0.6858094603597602, 'positive_rate': 0.4906081557273865, 'threshold': 0.5}

In [11]:
# BEST SAE
cfg = T.TrainConfig(epochs=30, batch_size=512, lr=best_sae['lr'], weight_decay=1e-4,
                    recon_weight=best_sae['recon_w'], clf_weight=best_sae['clf_w'])
sae, sae_hist = T.train_sae(
    X_train, y_train, X_val, y_val,
    in_features=X_train.shape[1], cfg=cfg,
    hidden_dims=tuple(best_sae['hidden']),
    latent_dim=int(best_sae['latent']),
    dropout=float(best_sae['dropout']),
)
p_sae_val  = T.predict_proba(sae, X_val)
p_sae_test = T.predict_proba(sae, X_test)
print('val :', E.classification_metrics(y_val,  p_sae_val))
print('test:', E.classification_metrics(y_test, p_sae_test))

# save for l8r (architecture metadata)
BEST_SAE_HIDDEN  = tuple(best_sae['hidden'])
BEST_SAE_LATENT  = int(best_sae['latent'])
BEST_SAE_DROPOUT = float(best_sae['dropout'])
BEST_MLP_HIDDEN  = tuple(best_mlp['hidden_dims'])
BEST_MLP_DROPOUT = float(best_mlp['dropout'])
print('saved config metadata:')
print('  MLP hidden:', BEST_MLP_HIDDEN, 'dropout:', BEST_MLP_DROPOUT)
print('  SAE hidden:', BEST_SAE_HIDDEN, 'latent:', BEST_SAE_LATENT, 'dropout:', BEST_SAE_DROPOUT)

epoch   1/30  train: loss=0.6466 recon=0.1242 clf=0.5224  val: loss=0.6216 recon=0.1027 clf=0.5189
epoch   2/30  train: loss=0.5577 recon=0.0929 clf=0.4648  val: loss=0.6187 recon=0.1003 clf=0.5184
epoch   3/30  train: loss=0.5351 recon=0.0909 clf=0.4443  val: loss=0.6102 recon=0.0993 clf=0.5109
epoch   4/30  train: loss=0.5114 recon=0.0884 clf=0.4230  val: loss=0.6042 recon=0.0981 clf=0.5062
epoch   5/30  train: loss=0.4861 recon=0.0872 clf=0.3989  val: loss=0.6185 recon=0.0977 clf=0.5208
epoch   6/30  train: loss=0.4562 recon=0.0870 clf=0.3693  val: loss=0.6491 recon=0.0975 clf=0.5515
epoch   7/30  train: loss=0.4177 recon=0.0868 clf=0.3309  val: loss=0.6521 recon=0.0976 clf=0.5545
epoch   8/30  train: loss=0.3746 recon=0.0866 clf=0.2880  val: loss=0.7214 recon=0.0975 clf=0.6239
epoch   9/30  train: loss=0.3339 recon=0.0865 clf=0.2474  val: loss=0.7665 recon=0.0986 clf=0.6678
epoch  10/30  train: loss=0.2927 recon=0.0863 clf=0.2064  val: loss=0.8546 recon=0.0979 clf=0.7567
epoch  11/30  train: loss=0.2602 recon=0.0861 clf=0.1740  val: loss=0.9891 recon=0.0979 clf=0.8912
epoch  12/30  train: loss=0.2326 recon=0.0860 clf=0.1466  val: loss=1.0595 recon=0.0977 clf=0.9618
epoch  13/30  train: loss=0.2143 recon=0.0859 clf=0.1285  val: loss=1.0570 recon=0.0977 clf=0.9593
epoch  14/30  train: loss=0.1941 recon=0.0858 clf=0.1083  val: loss=1.1233 recon=0.0973 clf=1.0259
epoch  15/30  train: loss=0.1786 recon=0.0856 clf=0.0929  val: loss=1.2046 recon=0.0971 clf=1.1075
epoch  16/30  train: loss=0.1677 recon=0.0856 clf=0.0821  val: loss=1.2372 recon=0.0971 clf=1.1401
epoch  17/30  train: loss=0.1613 recon=0.0855 clf=0.0758  val: loss=1.2839 recon=0.0971 clf=1.1868
epoch  18/30  train: loss=0.1495 recon=0.0854 clf=0.0641  val: loss=1.3653 recon=0.0975 clf=1.2678
epoch  19/30  train: loss=0.1455 recon=0.0853 clf=0.0603  val: loss=1.4381 recon=0.0968 clf=1.3413
epoch  20/30  train: loss=0.1391 recon=0.0852 clf=0.0539  val: loss=1.4546 recon=0.0970 clf=1.3576
epoch  21/30  train: loss=0.1373 recon=0.0852 clf=0.0521  val: loss=1.4254 recon=0.0967 clf=1.3287
epoch  22/30  train: loss=0.1357 recon=0.0851 clf=0.0506  val: loss=1.4002 recon=0.0969 clf=1.3034
epoch  23/30  train: loss=0.1342 recon=0.0850 clf=0.0492  val: loss=1.3825 recon=0.0969 clf=1.2856
epoch  24/30  train: loss=0.1294 recon=0.0850 clf=0.0445  val: loss=1.4900 recon=0.0967 clf=1.3933
epoch  25/30  train: loss=0.1269 recon=0.0850 clf=0.0420  val: loss=1.5180 recon=0.0966 clf=1.4214
epoch  26/30  train: loss=0.1267 recon=0.0849 clf=0.0418  val: loss=1.5401 recon=0.0966 clf=1.4434
epoch  27/30  train: loss=0.1221 recon=0.0848 clf=0.0373  val: loss=1.5113 recon=0.0967 clf=1.4147
epoch  28/30  train: loss=0.1217 recon=0.0847 clf=0.0370  val: loss=1.4891 recon=0.0965 clf=1.3926
epoch  29/30  train: loss=0.1191 recon=0.0847 clf=0.0344  val: loss=1.5358 recon=0.0966 clf=1.4392
epoch  30/30  train: loss=0.1197 recon=0.0846 clf=0.0351  val: loss=1.5359 recon=0.0965 clf=1.4394
val : {'auroc': 0.7867739094555503, 'auprc': 0.8030278978920249, 'f1': 0.7669024915410643, 'positive_rate': 0.5857002139091492, 'threshold': 0.5}
test: {'auroc': 0.7714204779387421, 'auprc': 0.7398529308838504, 'f1': 0.7057870802965178, 'positive_rate': 0.4906081557273865, 'threshold': 0.5}
saved config metadata:
  MLP hidden: (256,) dropout: 0.1
  SAE hidden: (512, 128) latent: 64 dropout: 0.2

## Step. 8 Further SAE experiments (spoiler: they all fail lol)

1. **Aggressive classification weight** (`clf_weight=10`, smaller latent)
2. **Two-stage training** (pretrain reconstruction, then add classifier)
3. **Large latent** (`latent=128`, `clf_weight=20`)

In [17]:
extra_records = [
    {'name': 'MLP best', 'val_auroc': roc_auc_score(y_val, p_mlp_val),
     'val_auprc': average_precision_score(y_val, p_mlp_val)},
    {'name': 'SAE best', 'val_auroc': roc_auc_score(y_val, p_sae_val),
     'val_auprc': average_precision_score(y_val, p_sae_val)},
]

# AGGRESSIVE CLASSIFICATION WEIGHT
print('\n SAE w/ aggressive clf weight')
cfg = T.TrainConfig(epochs=40, batch_size=512, lr=3e-4, weight_decay=1e-4,
                    recon_weight=0.1, clf_weight=10.0)
sae_agg, _ = T.train_sae(
    X_train, y_train, X_val, y_val,
    in_features=X_train.shape[1], cfg=cfg,
    hidden_dims=(256, 64), latent_dim=16, dropout=0.1,
)
p_agg_val = T.predict_proba(sae_agg, X_val)
extra_records.append({'name': 'SAE aggressive-clf',
                      'val_auroc': roc_auc_score(y_val, p_agg_val),
                      'val_auprc': average_precision_score(y_val, p_agg_val)})

 SAE w/ aggressive clf weight
epoch   1/40  train: loss=5.5318 recon=0.1400 clf=0.5518  val: loss=5.3367 recon=0.1036 clf=0.5326
epoch   2/40  train: loss=4.7991 recon=0.0955 clf=0.4790  val: loss=5.3122 recon=0.1037 clf=0.5302
epoch   3/40  train: loss=4.6621 recon=0.0949 clf=0.4653  val: loss=5.1696 recon=0.1047 clf=0.5159
epoch   4/40  train: loss=4.5092 recon=0.0954 clf=0.4500  val: loss=5.0499 recon=0.1056 clf=0.5039
epoch   5/40  train: loss=4.3615 recon=0.0959 clf=0.4352  val: loss=5.0836 recon=0.1065 clf=0.5073
epoch   6/40  train: loss=4.2135 recon=0.0966 clf=0.4204  val: loss=5.3413 recon=0.1082 clf=0.5330
epoch   7/40  train: loss=4.0322 recon=0.0972 clf=0.4022  val: loss=5.2353 recon=0.1092 clf=0.5224
epoch   8/40  train: loss=3.8294 recon=0.0975 clf=0.3820  val: loss=5.4679 recon=0.1091 clf=0.5457
epoch   9/40  train: loss=3.6148 recon=0.0979 clf=0.3605  val: loss=5.3938 recon=0.1086 clf=0.5383
epoch  10/40  train: loss=3.3405 recon=0.0980 clf=0.3331  val: loss=5.6590 recon=0.1095 clf=0.5648
epoch  11/40  train: loss=3.0484 recon=0.0983 clf=0.3039  val: loss=6.0348 recon=0.1100 clf=0.6024
epoch  12/40  train: loss=2.7641 recon=0.0988 clf=0.2754  val: loss=6.8622 recon=0.1087 clf=0.6851
epoch  13/40  train: loss=2.4558 recon=0.0990 clf=0.2446  val: loss=7.0416 recon=0.1093 clf=0.7031
epoch  14/40  train: loss=2.2039 recon=0.0993 clf=0.2194  val: loss=8.6227 recon=0.1107 clf=0.8612
epoch  15/40  train: loss=1.9372 recon=0.0994 clf=0.1927  val: loss=8.1263 recon=0.1115 clf=0.8115
epoch  16/40  train: loss=1.7381 recon=0.0994 clf=0.1728  val: loss=8.7288 recon=0.1118 clf=0.8718
epoch  17/40  train: loss=1.5287 recon=0.0995 clf=0.1519  val: loss=10.1785 recon=0.1121 clf=1.0167
epoch  18/40  train: loss=1.3665 recon=0.0996 clf=0.1357  val: loss=10.2997 recon=0.1113 clf=1.0289
epoch  19/40  train: loss=1.1932 recon=0.0994 clf=0.1183  val: loss=11.7813 recon=0.1114 clf=1.1770
epoch  20/40  train: loss=1.0672 recon=0.0992 clf=0.1057  val: loss=11.6217 recon=0.1110 clf=1.1611
epoch  21/40  train: loss=0.9379 recon=0.0991 clf=0.0928  val: loss=12.5773 recon=0.1109 clf=1.2566
epoch  22/40  train: loss=0.8809 recon=0.0990 clf=0.0871  val: loss=12.7181 recon=0.1114 clf=1.2707
epoch  23/40  train: loss=0.7718 recon=0.0989 clf=0.0762  val: loss=14.2639 recon=0.1114 clf=1.4253
epoch  24/40  train: loss=0.7103 recon=0.0990 clf=0.0700  val: loss=14.2566 recon=0.1119 clf=1.4245
epoch  25/40  train: loss=0.6287 recon=0.0990 clf=0.0619  val: loss=14.4342 recon=0.1118 clf=1.4423
epoch  26/40  train: loss=0.5819 recon=0.0991 clf=0.0572  val: loss=14.9443 recon=0.1118 clf=1.4933
epoch  27/40  train: loss=0.5534 recon=0.0992 clf=0.0544  val: loss=15.7059 recon=0.1115 clf=1.5695
epoch  28/40  train: loss=0.5112 recon=0.0992 clf=0.0501  val: loss=14.4469 recon=0.1134 clf=1.4436
epoch  29/40  train: loss=0.4700 recon=0.0993 clf=0.0460  val: loss=15.6267 recon=0.1129 clf=1.5615
epoch  30/40  train: loss=0.4552 recon=0.0993 clf=0.0445  val: loss=16.0833 recon=0.1131 clf=1.6072
epoch  31/40  train: loss=0.4076 recon=0.0993 clf=0.0398  val: loss=16.7435 recon=0.1150 clf=1.6732
epoch  32/40  train: loss=0.4093 recon=0.0994 clf=0.0399  val: loss=16.1147 recon=0.1142 clf=1.6103
epoch  33/40  train: loss=0.3619 recon=0.0994 clf=0.0352  val: loss=17.5510 recon=0.1134 clf=1.7540
epoch  34/40  train: loss=0.3561 recon=0.0996 clf=0.0346  val: loss=16.9626 recon=0.1148 clf=1.6951
epoch  35/40  train: loss=0.3492 recon=0.0997 clf=0.0339  val: loss=17.9509 recon=0.1138 clf=1.7939
epoch  36/40  train: loss=0.3646 recon=0.0996 clf=0.0355  val: loss=16.8337 recon=0.1143 clf=1.6822
epoch  37/40  train: loss=0.3154 recon=0.0995 clf=0.0305  val: loss=17.2068 recon=0.1149 clf=1.7195
epoch  38/40  train: loss=0.3178 recon=0.0996 clf=0.0308  val: loss=16.3916 recon=0.1136 clf=1.6380
epoch  39/40  train: loss=0.2994 recon=0.0995 clf=0.0289  val: loss=18.6142 recon=0.1138 clf=1.8603
epoch  40/40  train: loss=0.3080 recon=0.0996 clf=0.0298  val: loss=17.7290 recon=0.1140 clf=1.7718

In [18]:
# TWO STAGE TRAINING
print('\n Two-stage SAE (pretrain recon, then classifier)')
cfg1 = T.TrainConfig(epochs=20, batch_size=512, lr=1e-3,
                    recon_weight=1.0, clf_weight=0.0)
sae_pre, _ = T.train_sae(
    X_train, y_train, X_val, y_val,
    in_features=X_train.shape[1], cfg=cfg1,
    hidden_dims=(512, 128), latent_dim=32, dropout=0.2,
)
cfg2 = T.TrainConfig(epochs=20, batch_size=512, lr=3e-4)
sae_two, _ = T.train_sae_finetune(
    sae_pre, X_train, y_train, X_val, y_val,
    cfg=cfg2, freeze_encoder=False,
)
p_two_val = T.predict_proba(sae_two, X_val)
extra_records.append({'name': 'SAE two-stage',
                      'val_auroc': roc_auc_score(y_val, p_two_val),
                      'val_auprc': average_precision_score(y_val, p_two_val)})

 Two-stage SAE (pretrain recon, then classifier)
epoch   1/20  train: loss=0.1042 recon=0.1042 clf=0.7009  val: loss=0.0932 recon=0.0932 clf=0.7001
epoch   2/20  train: loss=0.0810 recon=0.0810 clf=0.6982  val: loss=0.0871 recon=0.0871 clf=0.6986
epoch   3/20  train: loss=0.0765 recon=0.0765 clf=0.6977  val: loss=0.0835 recon=0.0835 clf=0.6985
epoch   4/20  train: loss=0.0744 recon=0.0744 clf=0.6977  val: loss=0.0821 recon=0.0821 clf=0.6985
epoch   5/20  train: loss=0.0732 recon=0.0732 clf=0.6977  val: loss=0.0812 recon=0.0812 clf=0.6985
epoch   6/20  train: loss=0.0723 recon=0.0723 clf=0.6977  val: loss=0.0804 recon=0.0804 clf=0.6985
epoch   7/20  train: loss=0.0715 recon=0.0715 clf=0.6977  val: loss=0.0794 recon=0.0794 clf=0.6985
epoch   8/20  train: loss=0.0710 recon=0.0710 clf=0.6977  val: loss=0.0790 recon=0.0790 clf=0.6985
epoch   9/20  train: loss=0.0705 recon=0.0705 clf=0.6977  val: loss=0.0785 recon=0.0785 clf=0.6985
epoch  10/20  train: loss=0.0702 recon=0.0702 clf=0.6977  val: loss=0.0784 recon=0.0784 clf=0.6985
epoch  11/20  train: loss=0.0698 recon=0.0698 clf=0.6977  val: loss=0.0785 recon=0.0785 clf=0.6985
epoch  12/20  train: loss=0.0696 recon=0.0696 clf=0.6977  val: loss=0.0778 recon=0.0778 clf=0.6985
epoch  13/20  train: loss=0.0693 recon=0.0693 clf=0.6977  val: loss=0.0774 recon=0.0774 clf=0.6985
epoch  14/20  train: loss=0.0691 recon=0.0691 clf=0.6977  val: loss=0.0773 recon=0.0773 clf=0.6985
epoch  15/20  train: loss=0.0689 recon=0.0689 clf=0.6977  val: loss=0.0771 recon=0.0771 clf=0.6985
epoch  16/20  train: loss=0.0688 recon=0.0688 clf=0.6977  val: loss=0.0769 recon=0.0769 clf=0.6985
epoch  17/20  train: loss=0.0686 recon=0.0686 clf=0.6977  val: loss=0.0769 recon=0.0769 clf=0.6985
epoch  18/20  train: loss=0.0685 recon=0.0685 clf=0.6977  val: loss=0.0767 recon=0.0767 clf=0.6985
epoch  19/20  train: loss=0.0684 recon=0.0684 clf=0.6977  val: loss=0.0766 recon=0.0766 clf=0.6985
epoch  20/20  train: loss=0.0683 recon=0.0683 clf=0.6977  val: loss=0.0765 recon=0.0765 clf=0.6985
epoch   1/20  train=0.5853  val=0.5324
epoch   2/20  train=0.4815  val=0.5183
epoch   3/20  train=0.4663  val=0.5210
epoch   4/20  train=0.4547  val=0.5144
epoch   5/20  train=0.4439  val=0.4981
epoch   6/20  train=0.4329  val=0.5039
epoch   7/20  train=0.4208  val=0.5011
epoch   8/20  train=0.4104  val=0.5106
epoch   9/20  train=0.3969  val=0.5184
epoch  10/20  train=0.3833  val=0.5233
epoch  11/20  train=0.3676  val=0.5675
epoch  12/20  train=0.3486  val=0.5495
epoch  13/20  train=0.3272  val=0.5567
epoch  14/20  train=0.3046  val=0.5855
epoch  15/20  train=0.2766  val=0.6495
epoch  16/20  train=0.2493  val=0.7038
epoch  17/20  train=0.2246  val=0.7575
epoch  18/20  train=0.1966  val=0.7565
epoch  19/20  train=0.1709  val=0.8547
epoch  20/20  train=0.1535  val=0.9042

In [19]:
# LARGE LATENT & CLASSIFICATION WEIGHT
print('\nSAE w/ large latent, very strong clf weigh')
cfg = T.TrainConfig(epochs=40, batch_size=512, lr=3e-4, weight_decay=1e-4,
                    recon_weight=0.05, clf_weight=20.0)
sae_big, _ = T.train_sae(
    X_train, y_train, X_val, y_val,
    in_features=X_train.shape[1], cfg=cfg,
    hidden_dims=(512, 128), latent_dim=128, dropout=0.1,
)
p_big_val = T.predict_proba(sae_big, X_val)
extra_records.append({'name': 'SAE large-latent',
                      'val_auroc': roc_auc_score(y_val, p_big_val),
                      'val_auprc': average_precision_score(y_val, p_big_val)})

extras_df = pd.DataFrame(extra_records).sort_values('val_auroc', ascending=False)
extras_df.to_csv(Path(RESULTS_DIR) / 'sae_extra_experiments.csv', index=False)
extras_df

SAE w/ large latent, very strong clf weigh
epoch   1/40  train: loss=10.3197 recon=0.1286 clf=0.5157  val: loss=10.4313 recon=0.1057 clf=0.5213
epoch   2/40  train: loss=9.2321 recon=0.0966 clf=0.4614  val: loss=10.2002 recon=0.1095 clf=0.5097
epoch   3/40  train: loss=8.7320 recon=0.0977 clf=0.4364  val: loss=10.1132 recon=0.1085 clf=0.5054
epoch   4/40  train: loss=8.0697 recon=0.0987 clf=0.4032  val: loss=10.2551 recon=0.1133 clf=0.5125
epoch   5/40  train: loss=7.1727 recon=0.0994 clf=0.3584  val: loss=10.7154 recon=0.1138 clf=0.5355
epoch   6/40  train: loss=6.0109 recon=0.1004 clf=0.3003  val: loss=11.5965 recon=0.1137 clf=0.5795
epoch   7/40  train: loss=4.7669 recon=0.1010 clf=0.2381  val: loss=14.3705 recon=0.1137 clf=0.7182
epoch   8/40  train: loss=3.7372 recon=0.1014 clf=0.1866  val: loss=15.0857 recon=0.1157 clf=0.7540
epoch   9/40  train: loss=2.8964 recon=0.1014 clf=0.1446  val: loss=19.0105 recon=0.1150 clf=0.9502
epoch  10/40  train: loss=2.2263 recon=0.1015 clf=0.1111  val: loss=20.9014 recon=0.1163 clf=1.0448
epoch  11/40  train: loss=1.7102 recon=0.1017 clf=0.0853  val: loss=23.7895 recon=0.1144 clf=1.1892
epoch  12/40  train: loss=1.3260 recon=0.1020 clf=0.0660  val: loss=25.7676 recon=0.1153 clf=1.2881
epoch  13/40  train: loss=1.1490 recon=0.1019 clf=0.0572  val: loss=27.6930 recon=0.1154 clf=1.3844
epoch  14/40  train: loss=0.9632 recon=0.1020 clf=0.0479  val: loss=28.0598 recon=0.1146 clf=1.4027
epoch  15/40  train: loss=0.8349 recon=0.1020 clf=0.0415  val: loss=30.0553 recon=0.1162 clf=1.5025
epoch  16/40  train: loss=0.7394 recon=0.1020 clf=0.0367  val: loss=28.0450 recon=0.1164 clf=1.4020
epoch  17/40  train: loss=0.6938 recon=0.1022 clf=0.0344  val: loss=30.2739 recon=0.1179 clf=1.5134
epoch  18/40  train: loss=0.6231 recon=0.1022 clf=0.0309  val: loss=31.1383 recon=0.1180 clf=1.5566
epoch  19/40  train: loss=0.5332 recon=0.1023 clf=0.0264  val: loss=33.2380 recon=0.1179 clf=1.6616
epoch  20/40  train: loss=0.5511 recon=0.1024 clf=0.0273  val: loss=33.5264 recon=0.1180 clf=1.6760
epoch  21/40  train: loss=0.5081 recon=0.1024 clf=0.0251  val: loss=34.9421 recon=0.1181 clf=1.7468
epoch  22/40  train: loss=0.5145 recon=0.1024 clf=0.0255  val: loss=32.0522 recon=0.1172 clf=1.6023
epoch  23/40  train: loss=0.4615 recon=0.1022 clf=0.0228  val: loss=33.8460 recon=0.1181 clf=1.6920
epoch  24/40  train: loss=0.4899 recon=0.1024 clf=0.0242  val: loss=32.3958 recon=0.1194 clf=1.6195
epoch  25/40  train: loss=0.4150 recon=0.1023 clf=0.0205  val: loss=32.6218 recon=0.1195 clf=1.6308
epoch  26/40  train: loss=0.3552 recon=0.1023 clf=0.0175  val: loss=35.8391 recon=0.1170 clf=1.7917
epoch  27/40  train: loss=0.4096 recon=0.1025 clf=0.0202  val: loss=35.6317 recon=0.1200 clf=1.7813
epoch  28/40  train: loss=0.3920 recon=0.1024 clf=0.0193  val: loss=34.6951 recon=0.1190 clf=1.7345
epoch  29/40  train: loss=0.3704 recon=0.1023 clf=0.0183  val: loss=35.9219 recon=0.1180 clf=1.7958
epoch  30/40  train: loss=0.4165 recon=0.1024 clf=0.0206  val: loss=36.7365 recon=0.1175 clf=1.8365
epoch  31/40  train: loss=0.3742 recon=0.1023 clf=0.0185  val: loss=37.3009 recon=0.1174 clf=1.8648
epoch  32/40  train: loss=0.3539 recon=0.1024 clf=0.0174  val: loss=36.6110 recon=0.1195 clf=1.8303
epoch  33/40  train: loss=0.3404 recon=0.1024 clf=0.0168  val: loss=36.4461 recon=0.1175 clf=1.8220
epoch  34/40  train: loss=0.3322 recon=0.1024 clf=0.0164  val: loss=35.6837 recon=0.1187 clf=1.7839
epoch  35/40  train: loss=0.3070 recon=0.1024 clf=0.0151  val: loss=38.4090 recon=0.1179 clf=1.9202
epoch  36/40  train: loss=0.2814 recon=0.1023 clf=0.0138  val: loss=39.8760 recon=0.1181 clf=1.9935
epoch  37/40  train: loss=0.2810 recon=0.1026 clf=0.0138  val: loss=38.3901 recon=0.1174 clf=1.9192
epoch  38/40  train: loss=0.2747 recon=0.1024 clf=0.0135  val: loss=38.5800 recon=0.1195 clf=1.9287
epoch  39/40  train: loss=0.3073 recon=0.1025 clf=0.0151  val: loss=36.7754 recon=0.1192 clf=1.8385
epoch  40/40  train: loss=0.2613 recon=0.1025 clf=0.0128  val: loss=41.0085 recon=0.1179 clf=2.0501

                 name  val_auroc  val_auprc
0            MLP best   0.817006   0.846849
4    SAE large-latent   0.789664   0.810860
1            SAE best   0.786774   0.803028
3       SAE two-stage   0.780776   0.811694
2  SAE aggressive-clf   0.777199   0.800493

## Step 9. Final comparison + save predictions and checkpoints
Everything below is consumed by `04_evaluation_interpretation.ipynb` (yum ;p)

In [20]:
summary = []
for name, p_val, p_test in [
    ('logreg', p_logreg_val, p_logreg_test),
    ('mlp',    p_mlp_val,    p_mlp_test),
    ('sae',    p_sae_val,    p_sae_test),
    ('xgb',    p_xgb_val,    p_xgb_test),
]:
    summary.append({
        'model': name,
        'val_auroc':  roc_auc_score(y_val,  p_val),
        'val_auprc':  average_precision_score(y_val, p_val),
        'test_auroc': roc_auc_score(y_test, p_test),
        'test_auprc': average_precision_score(y_test, p_test),
    })
summary_df = pd.DataFrame(summary).set_index('model')
summary_df.to_csv(Path(RESULTS_DIR) / 'final_comparison.csv')
summary_df

        val_auroc  val_auprc  test_auroc  test_auprc
model
logreg   0.800273   0.814808    0.788197    0.751018
mlp      0.817006   0.846849    0.775779    0.738264
sae      0.786774   0.803028    0.771420    0.739853
xgb      0.831193   0.860131    0.810813    0.765829

In [21]:
preds = {
    'gene_names': gene_names,
    'y_val':  y_val,
    'y_test': y_test,
    'logreg': {'val': p_logreg_val, 'test': p_logreg_test,
               'coef': logreg.coef_.ravel()},
    'mlp':    {'val': p_mlp_val,    'test': p_mlp_test,
               'history': mlp_hist,
               'config': {'hidden_dims': BEST_MLP_HIDDEN,
                          'dropout': BEST_MLP_DROPOUT}},
    'sae':    {'val': p_sae_val,    'test': p_sae_test,
               'history': sae_hist,
               'config': {'hidden_dims': BEST_SAE_HIDDEN,
                          'latent_dim': BEST_SAE_LATENT,
                          'dropout': BEST_SAE_DROPOUT}},
    'xgb':    {'val': p_xgb_val,    'test': p_xgb_test,
               'feature_importance': xgb.feature_importances_},
}
with open(Path(RESULTS_DIR) / 'predictions.pkl', 'wb') as f:
    pickle.dump(preds, f)

torch.save(mlp.state_dict(), Path(RESULTS_DIR) / 'models' / 'mlp.pt')
torch.save(sae.state_dict(), Path(RESULTS_DIR) / 'models' / 'sae.pt')

print('saved:')
print('  results/predictions.pkl')
print('  results/models/mlp.pt')
print('  results/models/sae.pt')
print('  results/final_comparison.csv')
print('  results/hp_sweep.csv')
print('  results/sae_extra_experiments.csv')

saved:
  results/predictions.pkl
  results/models/mlp.pt
  results/models/sae.pt
  results/final_comparison.csv
  results/hp_sweep.csv
  results/sae_extra_experiments.csv